import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>esslam.dev</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <NavBar />
      hello
      <h1>Esslam Dev</h1>
    </main>

    <footer />
  </div>
);

export default Home;
